export const SELECCIONA_SERVICIO_PUBLICO = 'SELECCIONA_SERVICIO_PUBLICO';

/* TABS */

export const CAMBIAR_SECCION = 'CAMBIAR_SECCION'; 
export const CAMBIA_SPINNER = 'CAMBIA_SPINNER '

/* MERCADO */ 

export const CREA_MERCADO = 'CREA_MERCADO'; 
export const VALIDA_ESTADO_MERCADO = 'VALIDA_ESTADO_MERCADO'; 
export const LIMPIA_MERCADO = 'LIMPIA_MERCADO'
export const OBTENER_MERCADOS = 'OBTENER_MERCADOS'

/* PRODUCTOS */ 

export const AGREGA_PRODUCTOS = 'AGREGA_PRODUCTOS'; 
export const OBTENER_PRODUCTOS = 'AGREGA_PRODUCTOS'; 
export const LIMPIAR_ESTADO = 'LIMPIAR_ESTADO';

/* PRESUPUESTO */ 
export const OBTENER_PRESUPUESTO = 'OBTENER_PRESUPUESTO';
export const ACTUALIZAR_PRESUPUESTO = 'ACTUALIZAR_PRESUPUESTO'; 

/* TRANSACCIONES */ 
export const OBTENER_TRANSACCIONES  = 'OBTENER_TRANSACCIONES';